const RackDeviceNames = {
        WebserverSmall: 'WebserverSmall',
        CacheSmall: 'CacheSmall',
        DatabaseSmall: 'DatabaseSmall',
        SmallRackCooler: 'SmallRackCooler',
        WebserverMedium: 'WebserverMedium',
        CacheMedium: 'CacheMedium',
        DatabaseMedium: 'DatabaseMedium',
        WebserverLarge: 'WebserverLarge',
        CacheLarge: 'CacheLarge',
        DatabaseLarge: 'DatabaseLarge',
        WebserverX: 'WebserverX',
        DatabaseX: 'DatabaseX',
        CacheX: 'CacheX',
        FusionServer: 'FusionServer',
    },
    RackDevices = {
        WebserverSmall: {
            name: RackDeviceNames.WebserverSmall,
            units: 1,
            price: 1e4,
            clockRate: 100,
            power: 2500,
            producedHeat: 8,
            webserverThroughput: 200,
            requirements: {
                Firewall: 2,
                VirtualHardware: 2,
                OperatingSystem: 2,
            },
        },
        CacheSmall: {
            name: RackDeviceNames.CacheSmall,
            units: 1,
            price: 1e4,
            clockRate: 100,
            power: 2500,
            producedHeat: 6,
            cacheThroughput: 500,
            requirements: {
                Firewall: 2,
                VirtualHardware: 2,
                OperatingSystem: 2,
            },
        },
        DatabaseSmall: {
            name: RackDeviceNames.DatabaseSmall,
            units: 1,
            price: 1e4,
            clockRate: 100,
            power: 2500,
            producedHeat: 9,
            databaseThroughput: 300,
            requirements: {
                Firewall: 2,
                VirtualHardware: 2,
                OperatingSystem: 2,
            },
        },
        SmallRackCooler: {
            name: RackDeviceNames.SmallRackCooler,
            units: 1,
            price: 2e3,
            power: 2500,
            producedHeat: -15,
        },
        WebserverMedium: {
            name: RackDeviceNames.WebserverMedium,
            units: 2,
            price: 25e3,
            clockRate: 100,
            power: 4500,
            producedHeat: 10,
            webserverThroughput: 650,
            requirements: {
                Firewall: 4,
                VirtualHardware: 4,
                OperatingSystem: 4,
                ProcessManagement: 2,
                CronJob: 2,
            },
        },
        CacheMedium: {
            name: RackDeviceNames.CacheMedium,
            units: 2,
            price: 3e4,
            clockRate: 100,
            power: 4500,
            producedHeat: 10,
            cacheThroughput: 1200,
            requirements: {
                Firewall: 4,
                VirtualHardware: 4,
                OperatingSystem: 4,
                ProcessManagement: 2,
                CronJob: 2,
            },
        },
        DatabaseMedium: {
            name: RackDeviceNames.DatabaseMedium,
            units: 2,
            price: 3e4,
            clockRate: 100,
            power: 4500,
            producedHeat: 10,
            databaseThroughput: 800,
            requirements: {
                Firewall: 4,
                VirtualHardware: 4,
                OperatingSystem: 4,
                ProcessManagement: 2,
                CronJob: 2,
            },
        },
        WebserverLarge: {
            name: RackDeviceNames.WebserverLarge,
            units: 4,
            price: 15e4,
            clockRate: 100,
            power: 8e3,
            producedHeat: 12,
            webserverThroughput: 2500,
            requirements: {
                Firewall: 15,
                VirtualHardware: 15,
                OperatingSystem: 15,
                ProcessManagement: 4,
                CronJob: 4,
                ContinuousIntegration: 4,
            },
        },
        CacheLarge: {
            name: RackDeviceNames.CacheLarge,
            units: 4,
            price: 15e4,
            clockRate: 100,
            power: 8e3,
            producedHeat: 12,
            cacheThroughput: 5e3,
            requirements: {
                Firewall: 15,
                VirtualHardware: 15,
                OperatingSystem: 15,
                ProcessManagement: 4,
                CronJob: 4,
                ContinuousIntegration: 4,
            },
        },
        DatabaseLarge: {
            name: RackDeviceNames.DatabaseLarge,
            units: 4,
            price: 15e4,
            clockRate: 100,
            power: 8e3,
            producedHeat: 12,
            databaseThroughput: 4e3,
            requirements: {
                Firewall: 15,
                VirtualHardware: 15,
                OperatingSystem: 15,
                ProcessManagement: 4,
                CronJob: 4,
                ContinuousIntegration: 4,
            },
        },
        WebserverX: {
            name: RackDeviceNames.WebserverX,
            units: 8,
            price: 8e5,
            clockRate: 100,
            power: 14e3,
            producedHeat: 20,
            webserverThroughput: 21e3,
            requirements: {
                VirtualContainer: 8,
                Cluster: 5,
                SwarmManagement: 5,
            },
        },
        DatabaseX: {
            name: RackDeviceNames.DatabaseX,
            units: 8,
            price: 8e5,
            clockRate: 100,
            power: 14e3,
            producedHeat: 20,
            databaseThroughput: 3e4,
            requirements: {
                VirtualContainer: 8,
                Cluster: 5,
                SwarmManagement: 5,
            },
        },
        CacheX: {
            name: RackDeviceNames.CacheX,
            units: 8,
            price: 8e5,
            clockRate: 100,
            power: 14e3,
            producedHeat: 20,
            cacheThroughput: 42e3,
            requirements: {
                VirtualContainer: 8,
                Cluster: 5,
                SwarmManagement: 5,
            },
        },
        FusionServer: {
            name: RackDeviceNames.FusionServer,
            units: 16,
            price: 15e6,
            clockRate: 100,
            power: 84e3,
            producedHeat: 65,
            reducedPerformance: 90,
            overheatProtection: 95,
            webserverThroughput: 18e4,
            cacheThroughput: 15e4,
            databaseThroughput: 15e4,
            requirements: {
                VirtualContainer: 24,
                Cluster: 15,
                SwarmManagement: 15,
            },
        },
    };

export { RackDeviceNames, RackDevices };
